timeout: 600s

substitutions:
  _VERSION_REF: ${BRANCH_NAME}-${SHORT_SHA}
  _VERSION_BRANCH: ${_VERSION_REF//./-}
  _VERSION_TAG: ${TAG_NAME//./-}
  _VERSION_NAME: ${_VERSION_TAG:-$_VERSION_BRANCH}
  _TASK_MANAGER_MODULE_VERSION_NAME: "1.0-SNAPSHOT"

steps:
  - id: Build image
    name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: [
      'package', 'jib:build',
      '-Djib.to.image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_VERSION_NAME',
      '-Dspring.profiles.active=cloudrun'
    ]

  - id: Deploy the image to Cloud Run
    name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ['INSTANCE_CONNECTION_NAME_VALUE']
    entrypoint: 'bash'
    args:
      - "-cue"
      - |-
        gcloud run deploy $_SERVICE_NAME \
        --image gcr.io/$PROJECT_ID/$_SERVICE_NAME:$_TASK_MANAGER_MODULE_VERSION_NAME \
        --platform managed \
        --region $_REGION \
        --no-allow-unauthenticated \
        --add-cloudsql-instances $$INSTANCE_CONNECTION_NAME_VALUE

availableSecrets:
  secretManager:
    - versionName: ${_INSTANCE_CONNECTION_NAME_SECRET_VERSION_NAME}
      env: INSTANCE_CONNECTION_NAME_VALUE
